name: PowerShell Action
 
on: [push]
 
jobs:
  run-powershell:
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out code
      uses: actions/checkout@v2
 
    - name: Run PowerShell Script
      run: |
        pwsh -File myscript.ps1
